name: Trianglify

project:
  version: 1.0.0
  download_url:
  download_text:

license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title:
      icon:
      brand: false
      url:
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/royfrancis/trianglify
  footer:
    - title: Trianglify
      icon: github
      brand: true
      url: https://github.com/royfrancis/trianglify
    - title: Issues
      icon: bug
      url: https://github.com/royfrancis/trianglify/issues

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#4C979F"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#81b6bb"
      color2: "#4C979F"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'left'
      page: 'left'

social:
  github:
    enabled: false
    user:
    repo:
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google:

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
